[package]
name = "abcparser_peg"
version = "0.1.0"
description = "A parsing expression grammar (PEG) parser for ABC, written in Rust"
authors = ["Sean Bolton <sean@smbolton.com>"]
license = "MIT"

[dependencies]
pest = "^0.4.1"

[lib]
path = "src/abcparser_peg.rs"
crate-type = ["cdylib"]
